# application.yml (base comum para todos os perfis)
spring:
  application:
    name: barber-shop-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  devtools:
    remote:
      secret: 123
    restart:
      trigger-file: trigger.txt
