#application-prd.yml (usado com banco PostgreSQL na Railway)
spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: jdbc:postgresql://shinkansen.proxy.rlwy.net:20055/railway
    username: postgres
    password: edfryoiNyhogbwigMAnCqrMoMvFxtFbO
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
